[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["python3.12 -m pip install --upgrade pip", "python3.12 -m pip install -r facenet/requirements.txt"]

[phases.build]

[start]
cmd = "cd facenet && python3.12 -m gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 app:app"
