[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = ["pip install --upgrade pip setuptools wheel", "pip install -r facenet/requirements.txt"]

[phases.build]

[start]
cmd = "cd facenet && gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 app:app"
